### ISSUE TITLE
Tidy plotter arguments

### ISSUE THREAD

**Issue by utf** [WMD-group/PyTASER#12]
Why are `material_name`, `temp`, and `conc`, needed in the plotter? E.g. https://github.com/WMD-group/PyTASER/blob/953968c3f0044e79644744415b33647dc7b2dae3/plotter.py#L38

The docstring makes it sound like the temp will impact the plot but I don't think it should as the TAS has already been generated.

If these are just for additional labels and titles, then they should all be optional arguments with no default value (e.g., an empty string).

**Comment by savya10** [comment]
Done. The title will only be generated if ```material_name```, ```temp``` and ```conc``` are defined in the plotter - so people can generate without a title now.

**Comment by savya10** [comment]
Just wondering if it would be a good idea to just use an bool called `labels` to determine whether someone wants their graph labelled? If `True`, we could extract the info (material name, temp, conc, etc) from the container class instead of them having to type out the stuff. Or would that be too much potentially redundant info between classes (and babying the user)?
