### ISSUE TITLE
Auto mode for transition selection

### ISSUE THREAD

**Issue by utf** [WMD-group/PyTASER#14]
Currently the most painful thing is working out which transitions you need to select when plotting. I think it would be best to add an "auto" mode, that automatically works out which transitions are the most important for the energy range of interest, and then automatically labels those.

You would enable this mode by setting `relevant_transitions="auto"` in the plotter as an alternative to passing a list. 

And I think all of the examples, except one, should use "auto".

**Comment by savya10** [comment]
`"auto"` mode now shows the 3 most contributing band transitions for the TAS plot, or 2 most contributing for each JDOS. 
_(most contributing == maximum of the absolute absorption values associated with the transition is highest compared to other transitions)_
Option of passing a `relevant_transitions` list is still available.

I can also change the number of 'auto' plots to be shown in the plot if you think 3 is too many/too little. It might be useful to have this as a changeable parameter for the user. 
Additionally, I think it'd be beneficial to be able to pull out a list with the order of contribution from different transitions, so that the user can easily see the order of transitions. Happy to implement this if you think it would be useful.
